name: Checkmarx One Scan
on:
  pull_request:
    branches:
        - main
        - master
        - dev
        - test_166593
env:
 # platforms: Dockerfile
  scanTypes: iac-security,sast,sca
  threshold: iac-security-high=1=,iac-security-medium=1,iac-securitylow=1    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@2.0.18
        with:
          project_name: Margarita_ManualScan2_new
          cx_tenant: Cx_Seg
          base_uri: https://eu.ast.checkmarx.net
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --scan-types ${{ env.scanTypes }} --sca-filter '!**\Dockerfile'     
          #--sca-filter '!**\Dockerfile,!**\DockerFile' --debug --iac-security-platforms ${{ env.platform }}
         
